#!/usr/bin/env ruby
if ARGV.nil? || ARGV.size == 0
  puts "Usage: groute.rb PATTERN"
else
  search_term = ARGV.first
  groutes_store = File.expand_path('.groutes')
  routes_file = File.expand_path('config/routes.rb')
  unless File.exists?(groutes_store) && File.mtime(groutes_store) > File.mtime(routes_file)
    `bundle exec rake routes > .groutes`
  end
  puts `cat .groutes | grep #{search_term}`
end
