#!/bin/bash
if [ -n "$1" ] ; then
  PORT="$1"
else
  PORT='3000'
fi

cleanup(){
  echo "Killing unicorn server on port $PORT"
  ps aux | grep -vw grep | grep "unicorn_rails .*$PORT" | awk '{ print $2; }' | xargs kill -9
}

trap cleanup 2

echo "Starting unicorn server on port $PORT"
unicorn_rails -p $PORT -D
tail -f log/development.log